export const teamsData = {
  Laliga_Teams: [
    { id: 131, name: "Real Madrid" },
    { id: 144, name: "Athletic Bilbao" },
    { id: 133, name: "Villarreal" },
    { id: 132, name: "FC Barcelona" },
    { id: 136, name: "Espanyol" },
    { id: 140, name: "Getafe" },
    { id: 156, name: "Elche" },
    { id: 146, name: "Real Betis" },
    { id: 139, name: "Valencia" },
    { id: 174, name: "Rayo Vallecano" },
    { id: 168, name: "Alaves" },
    { id: 135, name: "Sevilla" },
    { id: 143, name: "Osasuna" },
    { id: 158, name: "Celta Vigo" },
    { id: 193, name: "Real Oviedo" },
    { id: 154, name: "Real Sociedad" },
    { id: 134, name: "Atletico Madrid" },
    { id: 142, name: "Mallorca" },
    { id: 150, name: "Levante" },
    { id: 175, name: "Girona" },
  ],
  EPL_Teams: [
    { id: 108, name: "Liverpool" },
    { id: 106, name: "Chelsea" },
    { id: 104, name: "Arsenal" },
    { id: 114, name: "Tottenham" },
    { id: 107, name: "Everton" },
    { id: 117, name: "Sunderland" },
    { id: 50, name: "Bournemouth" },
    { id: 10, name: "Crystal Palace" },
    { id: 105, name: "Manchester United" },
    { id: 29, name: "Nottingham Forest" },
    { id: 38, name: "Brighton" },
    { id: 36, name: "Leeds United" },
    { id: 110, name: "Manchester City" },
    { id: 12, name: "Burnley" },
    { id: 63, name: "Brentford" },
    { id: 113, name: "West Ham United" },
    { id: 116, name: "Newcastle United" },
    { id: 120, name: "Fulham" },
    { id: 109, name: "Aston Villa" },
    { id: 15, name: "Wolves" },
  ],
  SerieA_Teams: [
    { id: 234, name: "Napoli" },
    { id: 226, name: "Juventus" },
    { id: 225, name: "AS Roma" },
    { id: 290, name: "Cremonese" },
    { id: 229, name: "Udinese" },
    { id: 224, name: "Inter Milan" },
    { id: 236, name: "Lazio" },
    { id: 6117, name: "Como" },
    { id: 227, name: "AC Milan" },
    { id: 245, name: "Bologna" },
    { id: 228, name: "Fiorentina" },
    { id: 232, name: "Atalanta" },
    { id: 231, name: "Genoa" },
    { id: 248, name: "Pisa" },
    { id: 243, name: "Cagliari" },
    { id: 246, name: "Lecce" },
    { id: 241, name: "Parma" },
    { id: 316, name: "Hellas Verona" },
    { id: 235, name: "Torino" },
    { id: 266, name: "Sassuolo" },
  ],
  Ligue1_Teams: [
    { id: 480, name: "PSG" },
    { id: 465, name: "Lyon" },
    { id: 478, name: "Lille" },
    { id: 471, name: "Monaco" },
    { id: 481, name: "Lens" },
    { id: 479, name: "Strasbourg" },
    { id: 482, name: "Toulouse" },
    { id: 493, name: "Angers" },
    { id: 477, name: "Rennes" },
    { id: 469, name: "Olympique de Marseille" },
    { id: 485, name: "Le Havre" },
    { id: 470, name: "OGC Nice" },
    { id: 486, name: "Nantes" },
    { id: 476, name: "Auxerre" },
    { id: 472, name: "Lorient" },
    { id: 6075, name: "Paris FC" },
    { id: 534, name: "Brest" },
    { id: 484, name: "Metz" },
  ],
  UCL_Teams: [
    { id: 690, name: "Ajax" },
    { id: 104, name: "Arsenal" },
    { id: 232, name: "Atalanta" },
    { id: 144, name: "Athletic Bilbao" },
    { id: 134, name: "Atletico Madrid" },
    { id: 132, name: "FC Barcelona" },
    { id: 331, name: "Bayern Munich" },
    { id: 333, name: "Bayer Leverkusen" },
    { id: 341, name: "Borussia Dortmund" },
    { id: 106, name: "Chelsea" },
    { id: 337, name: "Eintracht Frankfurt" },
    { id: 945, name: "Galatasaray" },
    { id: 224, name: "Inter Milan" },
    { id: 226, name: "Juventus" },
    { id: 108, name: "Liverpool" },
    { id: 110, name: "Manchester City" },
    { id: 469, name: "Olympique de Marseille" },
    { id: 471, name: "Monaco" },
    { id: 234, name: "Napoli" },
    { id: 116, name: "Newcastle United" },
    { id: 1023, name: "Olympiacos" },
    { id: 480, name: "PSG" },
    { id: 725, name: "PSV Eindhoven" },
    { id: 131, name: "Real Madrid" },
    { id: 10564, name: "Kairat Almaty" },
    { id: 1204, name: "Union St. Gilloise" },
    { id: 133, name: "Villarreal" },
    { id: 890, name: "Sporting CP" },
    { id: 1789, name: "Slavia Praha" },
    { id: 114, name: "Tottenham" },
    { id: 1978, name: "Bodo Glimt" },
    { id: 2273, name: "Pafos FC" },
    { id: 7521, name: "Qarabag Agdam" },
    { id: 1824, name: "FC Copenhagen" },
    { id: 1169, name: "Club Brugge" },
    { id: 888, name: "Benfica" },
  ],
  BundesLiga_Teams: [
    {
      id: 331,
      name: "Bayern Munich",
    },
    {
      id: 337,
      name: "Eintracht Frankfurt",
    },
    {
      id: 350,
      name: "1. FC Köln",
    },
    {
      id: 341,
      name: "Borussia Dortmund",
    },
    {
      id: 359,
      name: "St. Pauli",
    },
    {
      id: 339,
      name: "Wolfsburg",
    },
    {
      id: 358,
      name: "FC Augsburg",
    },
    {
      id: 338,
      name: "Stuttgart",
    },
    {
      id: 351,
      name: "Hoffenheim",
    },
    {
      id: 392,
      name: "Union Berlin",
    },
    {
      id: 7171,
      name: "RB Leipzig",
    },
    {
      id: 333,
      name: "Bayer Leverkusen",
    },
    {
      id: 352,
      name: "Mainz 05",
    },
    {
      id: 349,
      name: "Borussia Mönchengladbach",
    },
    {
      id: 334,
      name: "Hamburger SV",
    },
    {
      id: 332,
      name: "Werder Bremen",
    },
    {
      id: 434,
      name: "FC Heidenheim",
    },
    {
      id: 354,
      name: "Freiburg",
    },
  ],
};
